### ISSUE TITLE
LDAP adminGroup not updating

### ISSUE THREAD

**Issue by Memorist23** [h44z/wg-portal#113]
Hi there

I'm still on version 1.0.8
we created the .env to go the a config.yml - it was all working when we initially installed it.
After restarting the system we've had a issue. The Admin users can no long get to the Admin page.
Also the default admin user doesn't seem to work either, the details from the config or the details from the service status.
the status is on 
`INFO[2022-08-22 20:55:49] starting ldap user synchronization...`
nothing past that.

Anythoughts?

Here is my config.yml

```
core:
  listeningAddress: 10.80.110.35:8123
  externalUrl: "myExternalURLhere"
  title: License Request
  ldapEnabled: True
  company: MyCompany
  adminUser: admin@wgportal.local
  adminPass: wgportal
  mailFrom: Wireguard <noreply@mycompany.com>
wg:
  devices:
    - wg0
  defaultDevice: wg0
  configDirectory: /etc/wireguard
email:
  host: 10.80.110.17
  port: 25
  tls: false
ldap:
  url: ldap://10.80.110.5:389
  dn: OU=Staff,OU=Users,OU=Active,OU=FB,DC=mycompany,DC=com,
  user: ldapbindwireguard@mycompany.com
  pass: a^u5AeyeM-epeis2M
  adminGroup: OU=IT,OU=Staff,OU=Users,OU=Active,OU=FB,DC=mycompany,DC=com
  # startTLS: false
```
