### ISSUE TITLE
Mail sending problem. Not resolved mail-servers ip.

### ISSUE THREAD

**Issue by Alexander-Kazandzhiyan** [h44z/wg-portal#149]
Hello
I deployed the portal with docker-compose with latest docker-image (web interface write `version master-3c2c7f3` )   and it works. Everything is ok, except for the problem with the mail.
Parameters is:

      - MAIL_FROM=WireGuard VPN <noreply+notification@mydomain.com>
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_ENCRYPTION=starttls
      - EMAIL_CERT_VALIDATION=false
      - EMAIL_AUTHTYPE=login
      - EMAIL_USERNAME=notification@mydomain.com
      - EMAIL_PASSWORD=mypassword
 
with `EMAIL_HOST=smtp.gmail.com` mail are not sended, but if i try to set `EMAIL_HOST=172.253.116.108` all works fine.

I did not have such problems with version 1.5, but we want to use actual version. What can i do do work with domain-name of mailhost?

**Comment by Alexander-Kazandzhiyan** [comment]
then i try to send config to email, i see error  : 
-------------------
500
Email error

failed to send email: failed to connect via SMTP: Mail Error on dialing with encryption type STARTTLS: dial tcp: lookup smtp.gmail.com: device or resource busy
--------------------

**Comment by h44z** [comment]
Can you try to mount the /etc/resolv.conf file into the container? Your docker-compose.yml should look something like:

```yaml
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:v1.0.16
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - /etc/resolv.conf:/etc/resolv.conf:ro
  ....
```

This way a DNS lookup inside the container should work...
