### ISSUE TITLE
Running without network mode host

### ISSUE THREAD

**Issue by lorenzopicoli** [h44z/wg-portal#156]
First of all thank you for the awesome project. I wanted to share my setup running wg-portal without `network_mode: host`. As answered [here](https://github.com/h44z/wg-portal/issues/109) and [here](https://github.com/h44z/wg-portal/issues/22) this project [needs to have access](https://github.com/h44z/wg-portal/issues/134#issuecomment-1365897351) to the `wg0` interface to properly run.

I run wireguard with the `linuxserver/wireguard` container and I'm installing `wg-portal` in the same container using their [custom scripts](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers). Here's how it looks like:

```
 - docker-compose.yml (with linuxserver/wireguard)
 - custom-cont.init.d
   - wireguard-portal-install.sh
 - custom-service-init.d
   - wireguard-portal.sh
```

Then in `docker-compose.yml`
```
- ./custom-cont-init.d/:/custom-cont-init.d/
- ./custom-services.d/:/custom-services.d/
```

To install wg-portal in `wireguard-porta-install.sh`

```
#!/usr/bin/with-contenv bash

echo "****** Installing wg-portal ******"
apt update
apt install golang-go -y
export PATH=$PATH:/usr/local/go/bin

git clone https://github.com/h44z/wg-portal.git /app/wg-portal-project
cd /app/wg-portal-project
# CGO_ENABLED=0 GOOS=linux /usr/lib/go-1.18/bin/go build -o wg-portal main.go
make build
cp ./dist/wg-portal /app/
rm -rf /app/wg-portal-project
```

And then in `wireguard-portal.sh` to run
```
#!/usr/bin/with-contenv bash
echo "SYSTEM SERVICE"
exec \
    /app/wg-portal
```

In the container logs there should be some errors which is wireguard-portal trying to init before wg0 is created, but right after it the server should be up and running.

As far as I'm aware the only drawback is that not running wg-portal in a container makes it harder to keep updated with something like `Watchtower`, but it was a requirement for me to run wg-portal behind traefik which is not in network_mode: host.

Created an issue since I'm not sure this is README-worthy, but let me know if there's any other way to do this or any other cons I'm missing.

Thanks!

**Comment by guillaume-cerf** [comment]
> Hi there,
I'm a newbie and i would like to reproduce your method:  be able to run both wirguard and wg-portal in the same container.
 
I tried to run them in their respective container with both of them linked by network_mode="host" but it does not seem to work entirely since i can't add new peers : error 500 "failed to prepare new peer: failed to get available IP addresses: no more available address from cidr".

So i'd like to give your method a try.

I'm using portainer to "manage" my container and more precisely the "stacks" option to copy paste docker compose file. 
I can't quite get around the protocol you post to do so, and would like to do it from the portainer interfaces if possible to be easier for futur maintenance ;)

Thanks for the hardwork everyone have put into making this app and thanks for your futur help :)

**Comment by guillaume-cerf** [comment]
Actually, after correctly reading the [custom scripts](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) from linuxserver your protocol was straight forward.
But i still have the same error 
![image](https://user-images.githubusercontent.com/108763259/227783122-9bf93a64-40b8-46e9-a816-a1f729e804e9.png)

I can't find anything about it :(

any idea ?

**Comment by karstennilsen** [comment]
I just linked networks of both containers:
```
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  wg-portal:
    image: h44z/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "service:wireguard"
```

**Comment by joestump** [comment]
@karstennilsen are you exposing a shared volume for `/etc/wireguard` or something? Wondering how wg-portal is writing files to the wireguard container in your example.

**Comment by Friday13th87** [comment]
@joestump did you find an answer to that?
the network mode from  @karstennilsen is not connecting the storage of both containers and it shouldnt work like that - i mean how should wg-portal install any new peers to the linuxserver container if its only sharing the same network...

**Comment by Real-Gecko** [comment]
Here're two ansible playbooks I've used to setup Wireguard and WG-Portal to work together, works flawlessly, WG-Portal was even able to import existing Wireguard peers, the only thing needed to update is peers' private key.
```yml
---
- name: Wireguard
  hosts: application
  gather_facts: false
  tasks:
    - name: Network
      community.docker.docker_network:
        name: wireguard-network
        driver: overlay
        attachable: true

    - name: Volume
      community.docker.docker_volume:
        name: wireguard-data

    - name: Container
      community.docker.docker_container:
        name: wireguard
        image: lscr.io/linuxserver/wireguard:latest
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        env:
          PUID=1000
          PGID=1000
          TZ=<desired TZ>
          SERVERURL=<ip or host name>
          PEERS=1
        mounts:
          - source: wireguard-data
            target: /config
            type: volume
          - source: /lib/modules/
            target: /lib/modules/
            type: bind
        ports:
          - 51820:51820/udp
          - 8123:8123
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
        networks:
          - name: wireguard-network
        userns_mode: host
        restart_policy: always
```
```yml
- name: WG Portal
  hosts: application
  gather_facts: false
  tasks:
    - name: Volume
      community.docker.docker_volume:
        name: wg-portal-data

    - name: Container
      community.docker.docker_container:
        image: wgportal/wg-portal:v1
        name: wg-portal
        restart_policy: always
        capabilities:
          - NET_ADMIN
        network_mode: container:wireguard
        volumes:
          - wireguard-data:/etc/wireguard
          - wg-portal-data:/app/data
        env:
          EXTERNAL_URL=http://<ip or host name>:8123
          ADMIN_USER=<admin user name>
          ADMIN_PASS=<admin pass>
          WG_CONFIG_PATH=/etc/wireguard/wg_confs # this bit is important
        userns_mode: host
```
My swarm setup works in `userns-remap` mode, thus I had to set `userns_mode: host`.

**Comment by Real-Gecko** [comment]
Also, default configs shall be added:
```
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
```

**Comment by bchardon** [comment]
Hello,

A few things were not clear for me:

wg-portal is only an interface to manage wireguard, but do not include wireguard.

So you need two docker containers: wg-portal and wireguard.

In my opinion the documentation should be improved to add a minimal, complete and working example of a docker compose setup.

**docker-compose:**

```
services:
  wireguard:
      image: lscr.io/linuxserver/wireguard:latest
      container_name: wireguard
      cap_add:
        - NET_ADMIN
      ports:
        - "51820:51820/udp"
        - "8888:8888" # Noticed that the port of the web UI is exposed in the wireguard container.
      volumes:
        - ./wg/wg-portal/etc/:/config # We share the configuration (wgx.conf) between wg-portal and wireguard
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      restart: unless-stopped

  wg-portal:
    image: wgportal/wg-portal:2.0.0-rc.1
    container_name: wg-portal
    restart: unless-stopped
    environment:
       - WG_CONFIG_PATH=/etc/wireguard/wg_confs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "service:wireguard" # So we ensure to stay on the same network as the wireguard container.
    volumes:
      - ./wg/wg-portal/etc:/etc/wireguard
      - ./wg/wg-portal/data:/app/data
      - ./wg/wg-portal/config:/app/config
```
      
**config.yml**

```
core:
  admin_user: myname
  admin_password: mysuperpassword
  admin_api_token: super-s3cr3t-api-token-or-a-UUID
  import_existing: true

web:
  site_title: BlaBla VPN
  site_company_name: Bla CORP
  listening_address: :8888
  csrf_secret: super-s3cr3t-csrf-wesh
  session_secret: super-s3cr3t-session-wesh
  request_logging: true
  external_url: https://vpn.mydomaine.com

advanced:
  config_storage_path: /etc/wireguard/
  start_cidr_v4: 10.8.0.0/24
  log_pretty: true
  expiry_check_interval: 30m
```


**reverse proxy**

Then i use caddy to reverse proxy the web ui:

```
vpn.mydomaine.com {
    reverse_proxy wireguard:8888
}
```

**Wg-Portal Interface configuration**

```
[Interface]

# Core settings
PrivateKey = xxx
Address = 10.8.0.1/24,fdfd:d3ad:c0de:1234::1/64

# Misc. settings (optional)
ListenPort = 51820
MTU = 1420
SaveConfig = true

# Interface hooks (optional)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE


[Peer]
PublicKey = xxx
PresharedKey = xxx
AllowedIPs = 10.8.0.2/32,fdfd:d3ad:c0de:1234::2/128
```

And I add `0.0.0.0/0` and `::/0 ` to the AllowedIP so the whole internet trafic go through the VPN.

For example one of my peer looks like:

```
[Peer]
PublicKey = xxx
Endpoint = vpn.mydomaine.com:51820
AllowedIPs = 10.8.0.0/24,fdfd:d3ad:c0de:1234::/64,0.0.0.0/0,::/0
PresharedKey = xxx
PersistentKeepalive = 16
```

And everything works fine now.
