### ISSUE TITLE
any example what to set adminGroup and so is_admin = 1 ?

### ISSUE THREAD

**Issue by jasonwee** [h44z/wg-portal#160]
I have the following trim down config.yaml

```
  adminGroup: cn=WireGuardAdmins,ou=Group,dc=acme,dc=com
  loginFilter: (&(objectClass=organizationalPerson)(uid={{login_identifier}}))
  syncFilter: (&(|(objectClass=inetOrgPerson)))
  syncGroupFilter: (objectClass=Group)
```

In the ldap, I have created WireGuardAdmins under Group and added a few users under this group. When I start wg-portal, it sync from ldap successfully but the flag for is_admin always 0. How to set that flag to one so I don't have to set it via sqlite ?

**Comment by philippderdiedas** [comment]
Correct me if I'm wrong, but in https://github.com/h44z/wg-portal/blob/master/internal/authentication/providers/ldap/provider.go#L147 the script iterates over the users groups and matches the admin group from the config. Assuming you don't have an Active Directory, you have to add memberOf=(admin group dn here) to your user in LDAP.

**Comment by Sarevok933219** [comment]
I have the same case. In our LDAP scheme we don't use memberOf attribute, but we have memberUid. And Portal can't match any groups only users. Please if it's possible give an extended example.

**Comment by h44z** [comment]
For **OAuth**, check the last comment in #317:

You need a property in the user-info response containing the string "true". This property must then be mapped to the is_admin property in the WireGuard Portal.

![image](https://github.com/user-attachments/assets/756555cb-3138-4952-8b95-b20c834be466)

![image](https://github.com/user-attachments/assets/2af9e2c7-9e33-42ff-b11a-e781cc80babb)

```yaml
auth:
  oauth:
    - id: google
      provider_name: google
      display_name: Google
      client_id: something-something.apps.googleusercontent.com
      client_secret: my-secret-key
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      user_info_url: https://openidconnect.googleapis.com/v1/userinfo
      scopes:
        - openid
        - email
        - profile
      field_map:
        email: email
        firstname: name
        user_identifier: sub
        is_admin: wgportal_admin
```



For **LDAP**, you need to specify the **admin_group** property. This value is then matched against the memberOf attribute in LDAP. If the user is a member of the group specified in the admin_group, admin access is granted.

Example value for the admin_group: CN=WireGuardAdmins,OU=_O_SomeOU,DC=EXAMPLE,DC=LOCAL
