### ISSUE TITLE
How to configure email for wg portal. env？

### ISSUE THREAD

**Issue by Pinkpiglet** [h44z/wg-portal#183]
How to configure email for wg portal. env？

**Comment by h44z** [comment]
via the config.yml file:

````yaml
mail:
  from: xyz@unknown.com
  host: 1.2.3.4
  ...
````

All configuration values can be seen in the [README.md](https://github.com/h44z/wg-portal/blob/master/README.md)
