### ISSUE TITLE
No peer default configuration created in V2

### ISSUE THREAD

**Issue by ebakoba** [h44z/wg-portal#189]
While using V2 it seems that no peer default configuration is created for the new user.

Reproduce steps:

1. Configured LDAP
2. Logged in with Admin account
3. Created a new interface under Interface Administration
4. Logged in as regular LDAP user

Expected behavior: default peer configuration be created for the LDAP user
Actual behavior: No default peer configuration generated for the regular LDAP user

**Comment by ebakoba** [comment]
@Bleala Sure!

In my conf file, I have following for LDAP:

```yml
auth:
  ldap:
    - id: ldap1
      start_tls: false
      cert_validation: false
      provider_name: CompanyName LDAP
      display_name: Login with</br>LDAP
      url: ldaps://authentik.company.net
      bind_user: "cn=wireguard-bind-service-username,ou=users,DC=ldap,DC=goauthentik,DC=io"
      bind_pass: "some_secret_pass"
      base_dn: dc=ldap,dc=goauthentik,dc=io
      login_filter: (&(objectClass=user)(mail={{login_identifier}}))
      admin_group: "cn=My Company Admins,ou=groups,dc=ldap,dc=goauthentik,dc=io"
      registration_enabled: true
```

I am using Auhtentik as my LDAP backend.
