### ISSUE TITLE
Issues with LDAP authentication

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [h44z/wg-portal#19]
We use FreeIPA as OpenLDAP provider to authenticate for wg-portal. Unfortunatly, logins are rejected without any error. May this be due to the use of `UID` (hence a username only) instead of a mail address?

This is our env file for LDAP
```bash
cat ldap.env 
# LDAP Settings
LDAP_ENABLED=true
LDAP_URL=ldap://X.X.X.X:389
LDAP_STARTTLS=false
LDAP_CERT_VALIDATION=false
LDAP_BASEDN=CN=users,CN=accounts,DC=XXXXX,DCc=XXXXX
LDAP_USER=UID=admin,CN=users,CN=accounts,DC=XXXXX,DC=XXXXX
LDAP_PASSWORD=AVeryStrongPassword
LDAP_ADMIN_GROUP=CN=admins,CN=users,CN=accounts,DC=XXXXX,DCc=XXXXX
LDAP_TYPE=OpenLDAP
#LDAP_USER_CLASS=inetOrgPerson
LDAP_ATTR_EMAIL=UID
```

We assume this issue comes from the `LDAP_ATTR_EMAIL=UID`. May this be correct and/or is there any solution? Or may this be due to the password comparison (server-side, we use B-Crypt)?

<details>
<summary> docker-compose.yml </summary>

```yaml
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:latest
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data/wg-portal:/app/data
    ports:
      - '8123:8123'
    env_file:
      - ldap.env
      - user.env
    environment:
      # WireGuard Settings
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      # Core Settings
      - EXTERNAL_URL=https://vpn.XXXX.XXXX
      - WEBSITE_TITLE=XXXX
      - COMPANY_NAME=XXXX
```

</details>

(Don't judge the plain text connection; it's a test setup only.)
