### ISSUE TITLE
Authelia and OIDC

### ISSUE THREAD

**Issue by MuratovAS** [h44z/wg-portal#192]
A few notes on setting up `oidc` with `authelia`. I didn't find the answer in this repository, I spent a lot of time setting it up.

In my network, the server has the domain `home.server`, services are located on subdomains `wgportal.home.server`.....

example:
`wgportal/config.yml`
```
web:
  # DO NOT TOUCH
  external_url: 

auth:
  callback_url_prefix:  https://wgportal.home.server/api/v0
  oidc:
    - id: Authelia
      provider_name: authelia
      display_name: Login with</br>Authelia
      base_url: https://authelia.home.server
      client_id: wgportal
      client_secret: # CREATE > openssl rand -hex 64
      field_map: 
        user_identifier: preferred_username
        email: email
        firstname: name
        # phone: 
        # lastname: 
        department: groups
      extra_scopes:
        - openid
        - profile
        - groups
        - email
      registration_enabled: true
```

`authelia/configuration.acl.yml`
```
identity_providers:
  oidc:
    clients:
    - id: wgportal
      description: wg-portal
      secret: '### client_secret from wg-portal ###'
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - https://wgportal.home.server/api/v0/auth/login/authelia/callback
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
```

It would be nice to add this information to the documentation

P.S. I think issues can be closed

**Comment by yash-k19** [comment]
How do i setup authila sso with xen-orchestra

**Comment by Stylee32** [comment]
For reference, in 2 years it has changed so the config needs to be different to work for Authelia (I suspect because Authelia is now openid certificated, so does OIDC correctly).

`config.yml`

```
auth:
  oidc:
    - id: Authelia
      provider_name: Authelia
      display_name: Login with</br>Authelia
      client_id: wgportal
      client_secret: <secret>
      base_url: https://auth.example.com
      field_map:
        user_identifier: preferred_username
        email: email
        firstname: name
        user_groups: groups
      admin_mapping:
        admin_group_regex: ^admin$
      extra_scopes:
        - openid
        - profile
        - groups
        - email
      registration_enabled: true
```

wg-portal only seems to connect to the token endpoint, and not the userinfo endpoint - which means that by default, only the bare essential is provided which means you can't map the scopes.

`configuration.yml`
```
claims_policies:
      wgportal_full:
        id_token: ['preferred_username', 'email', 'groups', 'name']
```

```
      - client_id: 'wgportal'
        client_name: 'wgportal'
        client_secret: '<secret>'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://wg.example.com/api/v0/auth/login/authelia/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        consent_mode: 'implicit'
        userinfo_signed_response_alg: 'none'
        claims_policy: 'wgportal_full'

```

The above will include all in the token endpoint to allow mapping in wg-portal (in my example, I am in the "admin" group which grants me admin in wg-portal
