### ISSUE TITLE
I can't log into the portal using my account.

### ISSUE THREAD

**Issue by garunoff** [h44z/wg-portal#198]
My container starts up normally, but for some unknown reason I can’t log into the portal under the user I specify in the config. When I try to login it says: "Login failed! Authentication failed!". 
Below I write the configs:

docker-compose.yml :
------------------------------
version: '3.6'
services:
  wg-portal:
    image: wgportal/wg-portal:master
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config

/app/wireguard-portal/config/config.yml
---------------------------------------------
core:
  admin_user: test@wg-portal.local
  admin_password: secret

web:
  external_url: http://localhost:8888
  request_logging: true

Please help me solve the problem.

**Comment by BliNeR-KeY** [comment]
pls check log

`docker logs wg-portal`

my config

```
web:
  external_url: http://wghome-home.ddns.net:8888
  request_logging: true
```
`

```
core:
  admin_user: MyUserName
  admin_password: MyPassword
```

Pls try to remove ./data/sqlite.db 
reboot server.

try to login again...

**Comment by garunoff** [comment]
In the logs there is only this:

time="2023-11-15T09:46:34Z" level=info msg="Starting WireGuard Portal V2..."
time="2023-11-15T09:46:34Z" level=info msg="WireGuard Portal version: unknown (local build)"

Deleting the database and restarting also does nothing.

**Comment by BliNeR-KeY** [comment]
> In the logs there is only this:
> 
> time="2023-11-15T09:46:34Z" level=info msg="Starting WireGuard Portal V2..." time="2023-11-15T09:46:34Z" level=info msg="WireGuard Portal version: unknown (local build)"
> 
> Deleting the database and restarting also does nothing.

on first install . you have once login details. you will get it from log.

**Comment by garunoff** [comment]
Sorry, but I didn't understand you. Can you explain in more detail?

**Comment by BliNeR-KeY** [comment]
> Sorry, but I didn't understand you. Can you explain in more detail?

if have no access in login. it means 


```
core:
  admin_user: admin
  admin_password: adminPass
```


or your config.yml not right place.

example...

if docker-compose.yaml are >> /home/Softwares/wg-portal/

you need to add config like this..

 /home/Softwares/wg-portal/config/config.yml


i'm using V2. works everything fine 
only have problem dont manage iptables i hope @h44z fill fix it without extra scripts around.


my wgportal/wg-portal:**latest**


```
version: '3.6'
services:
  wg-portal:
    image: wgportal/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config
#    restart: no
#    command: ["-migrateFrom=/app/data/wg_portal.db"]
```

**Comment by garunoff** [comment]
I do everything as you wrote, but the problem remains the same. The only thing that caught my attention was that you wrote not to manage iptables - what did you mean?

**Comment by BliNeR-KeY** [comment]
PostUp
PostDown
PreUp
PreDown

don't works from UI.  (maybe i wrong) but for me don't manage the shell

i open issue https://github.com/h44z/wg-portal/issues/194

hope @h44z will check to fix it.

**Comment by garunoff** [comment]
Got you. I don't use this in the config file. How can I view authentication logs?

**Comment by BliNeR-KeY** [comment]
> Got you. I don't use this in the config file. How can I view authentication logs?

- Without config file have once login details access as well I seen.
- please read back the config I give it's super easy 
- you can make log also json but need to active always from config file

**Comment by garunoff** [comment]
I read and applied the configuration you showed, but nothing helps.
Please show me an example of what you are saying about a log in JSON format.

**Comment by BliNeR-KeY** [comment]
> I read and applied the configuration you showed, but nothing helps. Please show me an example of what you are saying about a log in JSON format.

in  ./config/config.ym > advanced try to put like this.
```
advanced:
  log_level: debug
  config_storage_path: /etc/wireguard
  start_cidr_v4: 10.11.12.0/24
  start_listen_port: 51820
  log_pretty: true
  log_json: true
```
