### ISSUE TITLE
DNS Search Domain not applying

### ISSUE THREAD

**Issue by HPPinata** [h44z/wg-portal#211]
The ``DNS Search Domains`` field is not included in the generated configuration file despite being set (and applied) in the interface defaults and per client config.

Expected behaviour:
**Search domain included in .conf:** ``DNS = 192.168.8.1, lan``

Actual behaviour:
**Search domain not included in .conf:** ``DNS = 192.168.8.1``

The ``DNS Servers`` field works as expected, even with multiple entries setting ``,`` as necessary

Editing the generated .conf on the client manually to add the search domain works as expected (the core functionality appears to work without issues, just the .conf file generation needs some fixes)

I am aware of issue #46, but that discussed the viability of adding that option and also affected the UI (labeled "enhancement"), this is a bug report for an "existing" but broken feature

I am happy to provide more information and do some testing, but sadly was not able to find/fix this myself.

**Versions/Configuration:**
Running the Version 2 :latest docker image (hash: 9726fd3f1912f43f69aa591e5628d6e3590a2eb075cf217a96d3b715972ef28a)

config.yml is minimal:
```
advanced:
  log_level: trace

core:
  admin_user: mail@example.com
  admin_password: passwd
  import_existing: false

web:
  external_url: https://my.domain
  request_logging: true
```

Defaults:
![Screenshot 2024-02-05 113616](https://github.com/h44z/wg-portal/assets/83947761/c66c0926-e74c-423b-bc23-ef0ea6a94594)

Client:
![Screenshot 2024-02-05 113711](https://github.com/h44z/wg-portal/assets/83947761/4a04bccd-209a-488b-9f9a-1fb944511121)

File:
![Screenshot 2024-02-05 113748](https://github.com/h44z/wg-portal/assets/83947761/a3fb1f37-5e4c-429a-a339-ce6dd6ea749c)
