### ISSUE TITLE
EntraID/ Azure Auth issues

### ISSUE THREAD

**Issue by aeliusrs** [h44z/wg-portal#218]
hey there,

I'm trying to configure my AzureAD connectivity following the google OIDC config example, but I have the following error

![image](https://github.com/h44z/wg-portal/assets/25202393/fed8ce9d-1a83-4ecb-9407-3d219a5f88ff)

My configuration is the following :
```yaml
auth:
  callback_url_prefix: http://localhost:8888/api/v0
  oidc:
    - id: Microsoft
      provider_name: microsoft
      display_name: Login with</br>AzureAD
      base_url: https://login.microsoftonline.com
      client_id: "<client-id>"
      client_secret: "<client-secret>"
      extra_scopes:
        - https://login.microsoftonline.com/<microsoft-id>/oauth2/v2.0/authorize
      registration_enabled: true
```

I believe it would be helpful to have configuration example for major auth provider in the repository !

Cheers

**Comment by aeliusrs** [comment]
I'm trying with oauth also

```yaml
auth:
  oauth:
    - id: Microsoft
      provider_name: "azure_activedirectory_v2"
      display_name: "Login with</br>AzureAD"
      base_url: "https://login.microsoftonline.com/<client-id>/oauth2/v2.0"
      auth_url: "https://login.microsoftonline.com/<client-id>/v2.0/authorize"
      token_url: "https://login.microsoftonline.com/<client-id>/v2.0/token"
      scopes: ["openid", "profile", "email"]
      client_id: "<redacted>"
      client_secret: "<redacted>"
      registration_enabled: true
```

the button appear in the GUI but the generated link is really strange and result in a 404 error...

**Comment by aRobinTNS** [comment]
Hello, 
On my side I have configure with azure Entra Id as it : 
```yaml
 -  provider_name: azuread
    display_name: Azure AD
    base_url: https://login.microsoftonline.com/<tenant-id>/v2.0
    client_id: <your-client-id>
    client_secret: <your-secret>
    extra_scopes:
        - openid
        - profile
        - email
    field_map:
      email: email
      firstname: name
      user_identifier: preferred_username
      is_admin: roles
    registration_enabled: true
```

And it's work but the is_admin mapping didn't work because on the ParseUserInfo function of (auth_oidc.go)[https://github.com/h44z/wg-portal/blob/master/internal/app/auth/auth_oidc.go] the identification try to parse a field and microsoft entra Id send most of them as list.

**Comment by aeliusrs** [comment]
Wow thank you it almost work !

what did you configure for the return URI ?

**Comment by aeliusrs** [comment]
For the curious

in the config you should set 

```yaml
callback_url_prefix: https://your-example.com/api/v0
```

and in the redirect URI of microsoft application
```text
https://your-example.com/api/v0/auth/login/azuread/callback
```

**Comment by rquintanab** [comment]
Could you assist me with this issue? I'm encountering a 404 error, and when attempting to address it using the callback_prefix /auth/login, I'm receiving the error message: "redirect_uri' value must be a valid absolute URI" on Microsoft's page. I suspect this is something that needs adjustment in the configuration file. Could you provide guidance on resolving this? Additionally, could you share a portion of your configuration settings for reference?

**Comment by aRobinTNS** [comment]
> Could you assist me with this issue? I'm encountering a 404 error, and when attempting to address it using the callback_prefix /auth/login, I'm receiving the error message: "redirect_uri' value must be a valid absolute URI" on Microsoft's page. I suspect this is something that needs adjustment in the configuration file. Could you provide guidance on resolving this? Additionally, could you share a portion of your configuration settings for reference?

I confirm that your issue came from the Microsoft configuration side. The url that you have to put in microsoft is normaly like it : https://<Wireguard portal url>/api/v0/auth/login/azuread/callback

**Comment by rquintanab** [comment]
My redirect url on Microsoft side is: https://<my-domain.com>/api/v0/auth/login/azuread/callback

**Comment by aeliusrs** [comment]
It's correct

check my configuration

```yaml
core:
  admin_user: <admin-user>
  admin_password: <admin-pass>
  import_existing: false
  restore_state: true
  self_provisioning_allowed: true

web:
  external_url: https://<my-url>
  request_logging: true

auth:
  callback_url_prefix: https://<my-url>/api/v0
  oidc:
    - provider_name: azuread
      display_name: Azure AD
      base_url: "https://login.microsoftonline.com/<tenant-id>/v2.0"
      client_id: "<client-id>"
      client_secret: "<client-secret>"
      extra_scopes:
          - openid
          - profile
          - email
      field_map:
        email: email
        firstname: name
        user_identifier: preferred_username
        is_admin: roles
      registration_enabled: true
```
