### ISSUE TITLE
Run without network_mode: "host"

### ISSUE THREAD

**Issue by motey** [h44z/wg-portal#22]
Hi, 
first things first; Thanks for this great project! :heart: 

I am trying to find a way to run wg-portal in my specific setup, where i use traefik as a reverse proxy and for ssl termination.

This collides with the need to run wg-portal with the option `network_mode: "host"`

I am trying to run wg-portal, without host mode, with something like

```
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    #network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    ports:
    #  - '8123:8123'
      - 51820:51820/udp
    environment:
      # WireGuard Settings
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      # Core Settings
      - EXTERNAL_URL=https://vpn.company.com
      - WEBSITE_TITLE=WireGuard VPN
      - COMPANY_NAME=Your Company Name
      - ADMIN_USER=admin@domain.com
      - ADMIN_PASS=supersecret
      # Mail Settings
      - MAIL_FROM=WireGuard VPN <noreply+wireguard@company.com>
      - EMAIL_HOST=10.10.10.10
      - EMAIL_PORT=25
      # LDAP Settings
      - LDAP_ENABLED=true
      - LDAP_URL=ldap://srv-ad01.company.local:389
      - LDAP_BASEDN=DC=COMPANY,DC=LOCAL
      - LDAP_USER=ldap_wireguard@company.local
      - LDAP_PASSWORD=supersecretldappassword
      - LDAP_ADMIN_GROUP=CN=WireGuardAdmins,OU=Users,DC=COMPANY,DC=LOCAL
    networks:
     # network of reverse proxy 
      - front
      
    labels:
      - "treafik.enable=true"
      - "traefik.http.services.service-wg.loadbalancer.server.port=8123"
      - "traefik.http.routers.rt-wg.rule=Host(`vpn.company.com`)"
      - "traefik.http.routers.rt-wg.tls.certresolver=letsencrypt-resolver"
      - "traefik.http.routers.rt-wg.entrypoints=webtls"
networks:
  # network of reverse proxy 
  front:
    external: true
```

This routes port 8123 for the webinterface through the reverse proxy to a public domain (vpn.company.com) reachable via ssh/https.
Port 51820 for the wg stuff is still public via docker port expose.

But wg-portal crashes as it does get the wg device configured:
```
wg-portal    | FATA[2021-06-01 19:27:15] setup failed: unable to setup peer manager: unable to initialize peer manager: failed to get peer list for device wg0: could not get WireGuard device: file does not exist 
``` 

I dont get what i am missing here. In principle wireguard in a container does not seem to need full host network attachment, see https://hub.docker.com/r/linuxserver/wireguard

Do you have any ideas if and how i can workaround this issue?
