### ISSUE TITLE
Unable to find peer/record not found

### ISSUE THREAD

**Issue by Chris9667** [h44z/wg-portal#234]
Hi,

I'm still trying to use WireGuard with a LDAP configuration, for that I'm using ```"wgportal/wg-portal:2.0.0-alpha.1"``` as a docker image.
In WireGuard Portal on my profile when clicking on "Show Peer" I get an error saying:

```{"Code":500,"Message":"unable to find peer r\ufffd\ufffd: record not found"}``` and no data is shown (see images below)

For that my statistics in config.yml are on false, if I set them on true I get another error which I explained in my previous issue.
```
statistics:
  collect_peer_data: false
  collect_audit_data: false
  collect_interface_data: false
```
My config.yml file looks like this:
```
advanced:
  log_level: trace
  config_storage_path: /etc/wireguard

statistics:
  collect_peer_data: false
  collect_audit_data: false
  collect_interface_data: false

core:
  admin_user: admin
  admin_password: (hidden)
  import_existing: true

web:
  external_url: http://XX.XX.XX.XX:XXXX
  request_logging: false

auth:
  callback_url_prefix: http://XX.XX.XX.XX:XXXX/api/v0
  ldap:
    - id: ldap
      provider_name: (name)
      display_name: Login with</br>LDAP
      start_tls: false
      cert_validation: false
      url: ldaps://{{ redacted }}:636
      bind_user: uid={{ redacted }},cn=sysaccounts,cn=etc,{{ redacted }}
      bind_pass: {{ redacted }}
      base_dn: cn=accounts,{{ redacted }}
      login_filter: (&(objectClass=person)(memberof=cn=wgstudents,cn=groups,cn=accounts,{{ redacted }})(uid={% raw %}{{redacted}}{% endraw %}))
      admin_group: cn=admins,cn=groups,cn=accounts,{{ redacted }}
      field_map:
        user_identifier: uid
        firstname: givenname
        lastname: sn
        email: mail
        department: groups
      synchronize: true
      sync_filter: (memberof=cn=wgstudents,cn=groups,cn=accounts,{{ redacted }})
      registration_enabled: false
```

![Bild1](https://github.com/h44z/wg-portal/assets/156924911/8da4fc7e-ed0d-43aa-845c-392ae2f16a5b)
![Bild2](https://github.com/h44z/wg-portal/assets/156924911/b8102aef-841e-425c-8834-965af8086b5c)
![Bild3](https://github.com/h44z/wg-portal/assets/156924911/2b106d4c-2da7-4388-8c5f-2448fe1af056)
