### ISSUE TITLE
Can't delete oauth users or set them to admin

### ISSUE THREAD

**Issue by joestump** [h44z/wg-portal#259]
Ironically, I can delete myself as the admin. 😄 

When I log in as the main admin (as defined in `config.yml`), I am unable to upgrade privileges to users who've logged in via Authentik. The toggle is missing from the edit screen. 

<img width="812" alt="image" src="https://github.com/h44z/wg-portal/assets/37667/7b884ac8-244f-4c66-ad5d-981cf09f6e77">

I suspect it's just a component being gated? I looked at the code and there's a whole form with data being loaded, but I only see that when the user was created via DB.

**Comment by joestump** [comment]
If you point me in the right direction, I'll take a look at submitted a PR.

**Comment by bonddim** [comment]
Suppose, there is no toggle because user is synced from external provider, in your case Authentik. 
Try to use `is_admin` property in oauth/oidc config. 
But there is also bug - once user is created, permissions aren't updated on next login sync.

**Comment by joestump** [comment]
@bonddim I gave that a shot, but it's not working (I'm deleting the user in between sign ins; should be fresh `is_admin` on each login). 

```yaml
auth:
  callback_url_prefix: https://<my-url>/api/v0
  oidc:
    - id: authentik
      provider_name: authentik
      display_name: Login with Authentik
      base_url: https://id.stump.wtf/application/o/wireguard-portal/
      client_id: my-client-id
      client_secret: my-super-secret-client-secret
      extra_scopes:
        - profile
        - email
        - is_admin
      field_map:
        email: email
        user_identifier: email
      registration_enabled: true
```

I then have a Property Mapping with the scope `is_admin` in my Authentik:

```python
return str(ak_is_group_member(request.user, name="Administrators")).lower()
```

Here's the test output:

<img width="293" alt="image" src="https://github.com/h44z/wg-portal/assets/37667/245fe087-4863-4872-9803-285dfa2fb428">

Not quite sure where I went wrong. For now I'll manually update in the DB.

**Comment by joestump** [comment]
Gave it a shot with `oauth` and it leads to a 404 when I click the login button: `https://<my-wgportal-url>/api/v0/api/v0/authentik-oauth/init`. When I correct the double URI issue, it still 404s.

**Comment by bonddim** [comment]
@joestump ,
try to add `is_admin: "true"` into `field_map`

**Comment by bonddim** [comment]
@joestump, 
Correct, wg-portal expects boolean value to set admin permissions.

By providing `is_admin:` in `field_map` you set to which property in token scope to look for admin role.
If your authentick adds extra scope `is_admin: true`, it should work with 
```yaml
....
field_map:
  is_admin: is_admin
  ...
```
