### ISSUE TITLE
Instructions/example for `field_map`? 

### ISSUE THREAD

**Issue by vromero** [h44z/wg-portal#280]
Hi all,
 
I'm trying to configure wg-portal with Authentik using OIDC getting inspiration from #192.

However, when I use `field_map` with anything inside it I will get the following in the UI and absolutely nothing in the logs (even with `log_level: debug`:

![Captura de pantalla 2024-07-13 193803](https://github.com/user-attachments/assets/7a9359b9-1840-41f4-85f3-aa364088001f)

This is the `field_map` I'm using currently using:

```yaml
auth:
  callback_url_prefix:  https://xxx/api/v0
  oidc:
    - id: wgportal
      provider_name: wgportal
      display_name: xxx Auth
      base_url: https://xxx/application/o/wgportal/
      client_id: xxx
      client_secret: xxx
      registration_enabled: true
      field_map:
        user_identifier: preferred_username
        email: email
        firstname: given_name
        #lastname: given_name
        #phone:.
        department: given_name
        isAdmin: isAdmin
      extra_scopes:
        - users
```

And the following is the JWT payload returned by Authentik:

```json
{
    "iss": "https://xxx/application/o/wgportal/",
    "sub": "4e494e272e132b57ec84801b7ee35b5c7cc74b2e4d095d2096822eceb8e2094e",
    "aud": "acvgD9pRIlSmfCCFMH56iOw9NQqwg867hRzTePh6",
    "exp": 1720893678,
    "iat": 1720891878,
    "auth_time": 1720891878,
    "acr": "goauthentik.io/providers/oauth2/default",
    "amr": [
        "pwd"
    ],
    "email": "xxx@gmail.com",
    "email_verified": true,
    "isAdmin": true,
    "name": "authentik Default Admin",
    "given_name": "authentik Default Admin",
    "preferred_username": "admin",
    "nickname": "admin",
    "groups": [
        "authentik Admins",
        "ldapsearch",
        "Users"
    ]
}

Has anyone an example or instructions around how to field_map properly?

Thanks
```

**Comment by bonddim** [comment]
@vromero did you tried with other username?
I think, that there is conflict with default admin user and your admin user from OIDC

**Comment by vromero** [comment]
Thanks @bonddim, that is a great catch.

I tried, however, with some other user and had no luck. Got the exact same result.

**Comment by vromero** [comment]
Some additional information that I failed to mention. OIDC works just fine if I don't provide a `field_map`. I just need to do it to assign admin privileges to some users.

**Comment by bonddim** [comment]
one more...
Try to use `is_admin` instead of `isAdmin` property in your `field_map`:
```yaml
...
field_map:
  is_admin: isAdmin
```

**Comment by vromero** [comment]
Wow that's another excellent catch!

Unfortunately, it didn't help. 

Something that I notice is that the `user_identifier: preferred_username` seems to be some kind of inhibitor. If I leave it uncommented nothing works, if I comment it seems to work (but anything else in the section doesn't seem to have effect).

For instance the following does not work:

```yaml
      field_map:
        user_identifier: preferred_username
        #email: email
        #firstname: given_name
        #lastname: given_name
        #phone:
        #department: given_name
        #is_admin: isAdmin
```

And as you can see, the non-admin user I'm testing with now has preferred_username perfectly well defined:

```json
{
    "iss": "https://xxx/application/o/wgportal/",
    "sub": "56e5aa07a336ab4589d8faa96a0662a2be9261142d42ac2fcfa758e5c809242b",
    "aud": "acvgD9pRIlSmfCCFMH56iOw9NQqwg867hRzTePh6",
    "exp": 1720906073,
    "iat": 1720904273,
    "auth_time": 1720904273,
    "acr": "goauthentik.io/providers/oauth2/default",
    "amr": [
        "pwd"
    ],
    "email": "",
    "email_verified": true,
    "isAdmin": false,
    "name": "Perry",
    "given_name": "Perry",
    "preferred_username": "perry",
    "nickname": "perry",
    "groups": [
        "Users"
    ]
}
```
