### ISSUE TITLE
no work with ghcr.io/wg-easy/wg-easy:latest after update

### ISSUE THREAD

**Issue by DeAlexPesh** [h44z/wg-portal#292]
connected, but not routed...

wireguard.yml
```
version: "3"
name: wireguard
services:
 wireguard:
  image: ghcr.io/wg-easy/wg-easy:latest
  container_name: wireguard
  hostname: wireguard
  ports:
   - "0.0.0.0:51820:51820/udp" # WireGuard
#  - "0.0.0.0:51821:51821/tcp" # Portal Lite
   - "0.0.0.0:51822:51822/tcp" # Portal
  environment:
   - TZ=${TZ}
#  - PASSWORD=${PORTAL_PASSWORD}
   - PASSWORD_HASH=${PORTAL_PASSWORD_HASH}
   - WG_HOST=${WG_HOST}
   - WG_DEFAULT_ADDRESS=10.8.0.x
#  - WG_DEFAULT_DNS=192.168.1.2
#  - WG_DEFAULT_DNS=10.8.1.252
#  - WG_ALLOWED_IPS=192.168.0.0/16
   - WG_ALLOWED_IPS=0.0.0.0/0,::/0
   - WG_PORT=51820
   - WG_DEVICE=${WG_DEVICE}
#  - WG_MTU=1420
   - WG_PERSISTENT_KEEPALIVE=16
#  - UI_TRAFFIC_STATS=true
   - LANG=en
#  - WG_PRE_UP=
#  - WG_POST_UP=
#  - WG_PRE_DOWN=
#  - WG_POST_DOWN=
  volumes:
   - "/app/wg/wireguard:/etc/wireguard"
# depends_on:
#  pihole:
#   condition: service_healthy
  cap_add:
   - SYS_MODULE
   - NET_ADMIN
  sysctls:
   - net.ipv4.ip_forward=1
   - net.ipv4.conf.all.src_valid_mark=1
  healthcheck:
   test: ping -c 1 ${WG_HOST} || exit 1
   interval: 30s
   timeout: 10s
   retries: 3
  networks:
   vpn:
    ipv4_address: 10.8.1.2
  dns:
   - 192.168.1.2
  dns_search: *hide*
  logging:
   driver: "json-file"
   options:
    max-size: "200k"
    max-file: "5"
  restart: always

 portal:
  image: wgportal/wg-portal:1.0.19
  container_name: "portal"
  environment:
   - TZ=${TZ}
   - WG_DEVICES=${WG_DEVICE}
   - WG_DEFAULT_DEVICE=${WG_DEVICE}
   - CONFIG_FILE=/app/data/config.yml
   - EXTERNAL_URL=${WG_URL}
   - ADMIN_USER=${PORTAL_ADMIN}
   - ADMIN_PASS=${PORTAL_PASSWORD}
   - SESSION_SECRET=${SESSION_SECRET}
   - MAIL_FROM=${EMAIL_USERNAME}
   - EMAIL_USERNAME=${EMAIL_USERNAME}
   - EMAIL_PASSWORD=${EMAIL_PASSWORD}
   - LDAP_USER=${LDAP_USER}
   - LDAP_PASSWORD=${LDAP_PASSWORD}
   - LOG_LEVEL=debug
   - LOG_COLOR=false
   - LOG_JSON=false
  volumes:
   - "/app/wg/wireguard:/etc/wireguard"
   - "/app/wg/data:/app/data"
  depends_on:
   wireguard:
    condition: service_healthy
  cap_add:
   - NET_ADMIN
  network_mode: service:wireguard
  logging:
   driver: "json-file"
   options:
    max-size: "200k"
    max-file: "5"
  restart: always

networks:
 vpn:
  driver: bridge
  ipam:
   config:
    - subnet: 10.8.1.0/24
      gateway: 10.8.1.1
```

.env
```
TZ=Asia/Yekaterinburg
WG_DEVICE=wg0
WG_HOST=*hide*
WG_URL=http://*hide*
PORTAL_ADMIN=*hide*
PORTAL_PASSWORD=*hide*
PORTAL_PASSWORD_HASH=*hide*
SESSION_SECRET=*hide*
EMAIL_USERNAME=*hide*
EMAIL_PASSWORD=*hide*
LDAP_USER=*hide*@ente-ltd.ru
LDAP_PASSWORD=*hide*

```

config.yml
```
core:
  listeningAddress: 0.0.0.0:51822
  title: WireGuard
  company: *hide*
  logoUrl: *hide*
  editableKeys: true
  createDefaultPeer: true
  selfProvisioning: false
  wgExporterFriendlyNames: false
  ldapEnabled: true
  backgroundTaskInterval: 900
  expiryReEnable: false
email:
  host: *hide*
  port: 587
  tls: true
  encryption: tls
  certcheck: false
  auth: login
wg:
  configDirectory: /etc/wireguard
  manageIPAddresses: true
  userManagePeers: false
ldap:
  url: ldap://*hide*:389
  startTLS: false
  certcheck: false
  dn: dc=*hide*
  loginFilter: (&(objectClass=person)(mail={{login_identifier}}))
  syncFilter: (&(objectClass=person)(memberOf=cn=wUsers,ou=IT,dc=*hide*))
  syncGroupFilter: (objectClass=group)
  adminGroup: cn=wAdmins,ou=IT,dc=*hide*
  attrEmail: mail
  attrFirstname: givenName
  attrLastname: sn
  attrPhone: telephoneNumber
  attrGroups: memberOf
  ldapCertConn: false
```
