### ISSUE TITLE
What version am I running?

### ISSUE THREAD

**Issue by ilium007** [h44z/wg-portal#307]
UI shows this:
<img width="478" alt="image" src="https://github.com/user-attachments/assets/72489460-220f-4650-8518-fdde50d86cef">

My docker-compose.yml file:

```
❯ cat /srv/docker/docker-compose.yml
---
services:
  wg-portal:
    image: wgportal/wg-portal:latest
    container_name: wg-portal
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./wg-portal/data:/app/data
      - ./wg-portal/config:/app/config
    restart: unless-stopped

```

And from docker logs:

```
➜ docker logs -f wg-portal
time="2024-09-24T02:26:00Z" level=info msg="Starting WireGuard Portal V2..."
time="2024-09-24T02:26:00Z" level=info msg="WireGuard Portal version: master-ae1be0e"
```
