### ISSUE TITLE
Disabling AD Account does not disable user after LDAP Sync

### ISSUE THREAD

**Issue by Petelombardo** [h44z/wg-portal#344]
This is my sync filter:

sync_filter: (&(objectClass=organizationalPerson)(memberOf=CN=vpn_users,OU=Service Groups,OU=******,DC=******
,DC=local)(!userAccountControl:1.2.840.113556.1.4.803:=2)(!userAccountControl:1.2.840.113556.1.4.803:=16)(mail=*))

If I disable a user in Active Directory, the LDAP sync shows one less number of users sync'd, but the missing user is not disabled or deleted.   I tried with both the latest container published in dockerhub, as well as by building the container from the latest git.   Neither worked.

**Comment by h44z** [comment]
Hi, can you please post some logs (trace level) and your ldap provider config (without sensitive content).  Have you set the **disable_missing** flag to true?

**Comment by h44z** [comment]
tested in [v2.0.0-beta.3](https://github.com/h44z/wg-portal/releases/tag/v2.0.0-beta.3), cant see a problem

**Comment by Petelombardo** [comment]
How does the feature work?   Should the LDAP filter be set to filter out
locked or disabled users and then should the disable missing users setting
allow the system to automatically disable users who did not show up in the
last sync?

This is what I tested but could not get working.  Can you share a working
config that I can compare against?

**Comment by h44z** [comment]
I will release a new beta soon, including a fix for that bug. 

A working authentication provider configuration looks like this:

```yaml
auth:
  ldap:
    - id: ldap
      provider_name: ad
      display_name: Login with</br>AD
      url: ldap://srv-ad1.company.local:389
      bind_user: ldap_wireguard@company.local
      bind_pass: top-s3cret-pw
      base_dn: DC=COMPANY,DC=LOCAL
      login_filter: (&(objectClass=organizationalPerson)(mail={{login_identifier}})(!userAccountControl:1.2.840.113556.1.4.803:=2))
      admin_group: CN=WireGuardAdmins,OU=Service Groups,DC=COMPANY,DC=LOCAL
      sync_interval: 5m
      disable_missing: true
      sync_filter: (&(objectClass=organizationalPerson)(!userAccountControl:1.2.840.113556.1.4.803:=2)(mail=*))
      registration_enabled: true
```

This config uses default field mappings for the active directory. It will sync users every 5 minutes.

The cause of the issue was the missing provider_name field in the user database (all users have a blank provider name assigned).
Thus, missing users are not disabled, as the provider did not match. **For the fix to apply, you must manually correct the database entries and set the provider_name column accordingly.**

For the example above, the configured provider name is `ad`. Thus the ldap users in the database must have the provider_name column set to `ad`:

![Image](https://github.com/user-attachments/assets/c40cb13c-cd9d-4c53-99cf-0d129b3875fa)
