### ISSUE TITLE
Long time load web-ui

### ISSUE THREAD

**Issue by viktor-zharikov** [h44z/wg-portal#364]
After some experimental with wg-portal v2 in docker compose web ui extremly long loading time 
try to use incontito mode in browser, its not hapfuly

![Image](https://github.com/user-attachments/assets/9eb4b7ed-a33e-4c51-9b9f-da9ef15267b7)
![Image](https://github.com/user-attachments/assets/5aa6fd3c-5d15-44d7-bb09-5279a40a504e)

try to use v2.0.0-beta.7 its same

```
---
services:
  wg-portal:
    image: wgportal/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    ports:
      - "51889:51820/udp"
      - "8888:8888/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
#    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config
#    restart: no
#    command: ["-migrateFrom=/app/data/wg_portal.db"]`
```

config.yaml
```
  admin_user: admin
  admin_password: admin
#  admin_api_token: super-s3cr3t-api-token-or-a-UUID
  import_existing: true
  create_default_peer: false
  self_provisioning_allowed: false

web:
  site_title: My WireGuard Server
  site_company_name: test
  listening_address: :8888
  external_url: http://10.90.2.202:8888
#  csrf_secret: super-s3cr3t-csrf
#  session_secret: super-s3cr3t-session
  request_logging: true

advanced:
  log_level: info
  log_pretty: true
  log_json: true
  config_storage_path: /etc/wireguard
  expiry_check_interval: 5m
  start_cidr_v4: 10.11.12.0/23
  use_ip_v6: false
database:
  debug: true
  type: sqlite
  dsn: data/sqlite.db
```
