### ISSUE TITLE
Error synchronizing users, fails to serialize/deserialize uint8 to time

### ISSUE THREAD

**Issue by Freddo3000** [h44z/wg-portal#369]
**Describe the bug**

wg-portal fails to serialize uint8 into Time.

```console
TRAC[0259] fetched 296 raw ldap users from provider LDAP... 
ERRO[0259] SELECT * FROM `users` WHERE `users`.`identifier` = '<name>' ORDER BY `users`.`identifier` LIMIT 1  duration=1.673324ms error="sql: Scan error on column index 2, name \"created_at\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" rows=1 src="/build/internal/adapters/database.go:713"
ERRO[0259] failed to synchronize LDAP users for LDAP: find error for user id <name>: sql: Scan error on column index 2, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time 
TRAC[0259] starting to synchronize users for LDAP 
TRAC[0259] fetched 296 raw ldap users from provider LDAP... 
ERRO[0259] SELECT * FROM `users` WHERE `users`.`identifier` = '<name>' ORDER BY `users`.`identifier` LIMIT 1  duration=6.92749ms error="sql: Scan error on column index 2, name \"created_at\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" rows=1 src="/build/internal/adapters/database.go:713"
ERRO[0259] failed to synchronize LDAP users for LDAP: find error for user id <name>: sql: Scan error on column index 2, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time 
``` 

Repeat ad infinitum

**Expected behavior**

Data being correctly stored in and fetched from the database?

**Steps to reproduce**

LDAP configuration:

```yaml
# config.yaml
...
auth:
  ldap:
    - id: ldap
      provider_name: LDAP
      display_name: Login with</br>LDAP
      url: ldaps://<uri>

      base_dn: dc=ludd,dc=ltu,dc=se
      admin_group: <admin_group_dn>
      bind_user: <bind_dn>
      bind_pass: <bind_pass>

      login_filter: "<loginf_filter>"
      registration_enable: true

      synchronize: true
      sync_interval: 1800
      sync_filter: "<filter>"
      disable_missing: true
      field_map:
        user_identifier: uid
        email: mail
        firstname: givenName
        lastname: sn
        phone: mobile
        department: ou
        memberof: memberOf

      start_tls: true
      cert_validation: false
...
```
Some values censored as can be seen.

**Screenshots**

**Additional context**

- Application version: Latest docker
- Install method: docker
- OS: Linux

Database server used: MariaDB
LDAP backend: OpenLDAP
