### ISSUE TITLE
Can't create an interface in client mode

### ISSUE THREAD

**Issue by jkunczik** [h44z/wg-portal#371]
**Describe the bug**
First of all, thank you so much for this project! I tried a lot of wireguard UIs, but this one is the perfect mix of simplicity and configurability. 

Running a wireguard interface in "server mode" works perfectly. However, when I try to create an interface in "client mode", I am not able to create a peer. When I try to add a new peer, I get the warning "Backend connection failure failed to load prepared peer!". The debug console shows "Failed to load prepared peer:  self provisioning is only allowed for server interfaces: no permission".

When trying to save the configuration, I get the error "Failed to save peer! interface id mismatch"

**Expected behavior**
I am expecting to create a peer to describe the connection to the remote VPN server (endpoint adess, keys etc.). When saving the peer, it should be added to the wg.conf of the corresponding wireguard interface in client mode.  

**Steps to reproduce**
- Run wg-portal using Docker compose:
```
services:
  wg-portal:
    image: wgportal/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config
```
- create a wireguard interface in client mode
- try to create a peer to describe the endpoint to connect to

**Additional context**
- Application version: master-5697c2b
- Install method: docker
