### ISSUE TITLE
[Helm] provide option to inject secret configuration in a GitOps friendly way

### ISSUE THREAD

**Issue by ixxeL2097** [h44z/wg-portal#378]
**Is your feature request related to a problem? Please describe.**

Currently Wireguard config is stored in a Kubernetes `Secret` as a whole `config.yaml` multi-line string that you can customize with the helm `config` key in the `values.yaml` file. For those of us who use GitOps method like ArgoCD or FluxCD, it is not acceptable to push some of the information to git (OIDC client secret for example, or others).
Is there already solution to provide our own `Secret` ? 

**Describe the solution you'd like**

Usual solution is to provide a already provisioned `Secret` for example with `ExternalSecret`. That would be nice to have a key like `config.existingSecret` to let the user provide the configuration with his own method.

I would like to be able to provision my configuration from this kind of solution and let the wireguard deployment mount my `Secret`.

**Describe alternatives you've considered**

**Additional context**

**Comment by bonddim** [comment]
@ixxeL2097 , hi
The chart is already compatible with GitOps deployments via Argo CD or FluxCD. 

You may reference sensitive data like OIDC client secret from other secret and wg-portal will do env substitution on config. 

Example:
```yaml
# Use environment variables for client_id and client_secret properties:
config:
  auth:
    oidc:
      - id: oidc
        client_id: "${WG_PORTAL_CLIENT_ID}"
        client_secret: "${WG_PORTAL_CLIENT_SECRET}"
        ...

# Provide env variables by key  from some external secret
env:
  - name: WG_PORTAL_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: external-vault
        key: wgPortalClientId

  - name: WG_PORTAL_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: external-vault
        key: wgPortalClientSecret

# or  reference all keys from external secret
envFrom:
  - secretRef:
      name: external-vault

# Deploy SecretStore and ExternalSecret resources within the chart:
extraDeploy:
  - apiVersion: external-secrets.io/v1beta1
    kind: SecretStore
    metadata:
      name: external-vault
    spec:
      provider:
        ...

  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: external-vault
    spec:
      secretStoreRef:
        kind: SecretStore
        name: external-vault
      data:
        - secretKey: WG_PORTAL_CLIENT_ID
          remoteRef:
            key: wgPortalClientId
        - secretKey: WG_PORTAL_CLIENT_SECRET
          remoteRef:
            key: wgPortalClientSecret
```

Hope, this will help you on your GitOps way :)
