### ISSUE TITLE
[OIDC] Can't make user admin with oidc/authentik with is_admin parameter

### ISSUE THREAD

**Issue by ixxeL2097** [h44z/wg-portal#381]
Has OIDC admin connexion been fixed ? Cause I can't make it work even with static value assigned to `id_admin` field. I tried multiple different configuration but everytime I get a non admin user. 

I tried this configuration first trying to follow what was said in [issue #259 ](https://github.com/h44z/wg-portal/issues/259) with python script in Authentik which returns `"true"` but also tried with `true` or `1`, nothing actually works.

```python
return str(ak_is_group_member(request.user, name="wireguard admins")).lower()
```
```yaml
  config:
    core:
      admin_user: '${ADMIN_USER}'
      admin_password: '${ADMIN_PASSWORD}'
      import_existing: false
      create_default_peer: true
      self_provisioning_allowed: true

    auth:
      callback_url_prefix: https://wireguard.example.com/api/v0
      oidc:
        - id: Authentik
          provider_name: Authentik
          display_name: OIDC Authentik
          base_url: https://authentik.example.com/application/o/wireguard/
          client_id: '${OIDC_CLIENT_ID}'
          client_secret: '${OIDC_CLIENT_SECRET}'
          extra_scopes:
            - profile
            - email
            - openid
            - is_admin
          field_map:
            email: email
            user_identifier: email
            is_admin: is_admin
          registration_enabled: true
```

I also tried to set it strratically : 
```yaml
        extra_scopes:
          - profile
          - email
          - openid
          - is_admin
        field_map:
          email: email
          user_identifier: email
          is_admin: true
        registration_enabled: true
```
But still it never works, I always get a `0` numeric value in the SQLite `is_admin` column : 
```console
sqlite> SELECT * FROM users;
_WG_SYS_ADMIN_|_WG_SYS_ADMIN_|2025-02-27 16:37:29.402257752+00:00|2025-02-27 16:37:29.402867454+00:00|user1@gmail.com|user1@gmail.com|oauth|Authentik|0|user1|||||||||||
_WG_SYS_ADMIN_|_WG_SYS_ADMIN_|2025-02-27 17:05:09.516703393+00:00|2025-02-27 17:05:09.518266477+00:00|root|admin@wgportal.local|db||1|WireGuard Portal|Admin|||default administrator user|xxxxxxxxxxxxxxxxxxxxxxxxxxx||||||
```
I even tried to put admin numeric value of `1` directly in SQLite DB but it gets overwritten once I login.

I'm running a bit out of ideas so if someone could help me I would be grateful.

Environment:
Helm chart :  `0.7.0`
image: `wgportal/wg-portal:v2`
