### ISSUE TITLE
does not allow access to the admin panel with the default login

### ISSUE THREAD

**Issue by zlukaUA** [h44z/wg-portal#406]
- Debian GNU/Linux 12 (bookworm)
- wg-portal_linux_amd64 
- [v2.0.0-beta.7]

do not work by default:
- admin@wgportal.local
- wgportal

**Comment by h44z** [comment]
@zlukaUA can you please post some logs and your config.yml?

If you set a custom user/password in your config, those settings must be used to log in:

```yaml
core:
  admin_user: test@test.de
  admin_password: secret
```
