### ISSUE TITLE
[DOCUMENTATION] LDAP settings example contains display_name

### ISSUE THREAD

**Issue by xpufx** [h44z/wg-portal#408]
In my testing with ldap sync/auth the login screen does not display any LDAP related label etc. As expected both local and ldap logins work through the same login page and input fields. Is this an old setting that doesn't apply to ldap anymore? If so, it might be good to remove it from the example. Also please confirm that there are no explicit ldapEnabled or LDAP_ENABLED anymore? I've seen these in the issues but not in the current documentation.

```
# ... (basic configuration)

auth:
  ldap:
    # a sample LDAP provider with user sync enabled
    - id: ldap
      provider_name: Active Directory
      display_name: Login with</br>AD
      url: ldap://srv-ad1.company.local:389
      bind_user: ldap_wireguard@company.local
      bind_pass: super-s3cr3t-ldap
      base_dn: DC=COMPANY,DC=LOCAL
      login_filter: (&(objectClass=organizationalPerson)(mail={{login_identifier}})(!userAccountControl:1.2.840.113556.1.4.803:=2))
      sync_interval: 15m
      sync_filter: (&(objectClass=organizationalPerson)(!userAccountControl:1.2.840.113556.1.4.803:=2)(mail=*))
      disable_missing: true
      field_map:
        user_identifier: sAMAccountName
        email: mail
        firstname: givenName
        lastname: sn
        phone: telephoneNumber
        department: department
        memberof: memberOf
      admin_group: CN=WireGuardAdmins,OU=Some-OU,DC=COMPANY,DC=LOCAL
      registration_enabled: true
      log_user_info: true
```
