### ISSUE TITLE
[help req.] bridged docker interface

### ISSUE THREAD

**Issue by PizzaProgram** [h44z/wg-portal#428]
I need a little help.
According to the [doc](https://wgportal.org/master/documentation/getting-started/docker/#wireguard-interface-handling) I'm trying to switch from:
```yaml
services:
  wg-portal:
    ...
    network_mode: "host"
    ...
```
to the 2th (recommended) mode:
```yaml
    ports:
      - "2221:2221/udp" 
      - "2222:2222/udp" 
      # Web UI port
      - "127.0.0.9:18888:18888/tcp" # <--- Use / Uncomment this line to restrict access to a localhost port only
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wg-docker-nat

networks:
  wg-docker-nat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.22.0/24
```

It will start, but will not work. In the starting Log I see:
```log
2025/05/04 17:10:51 ERROR failed to synchronize routes source=interface updated: wg0 error=failed to find physical link for wg1: Link not found
```

### 2.
The other problem is, how to bind the Web UI? If I try to change binging of web serving port, to the docker IP:
` - "172.31.22.0:18888:18888/tcp"`
Stack will not start at all:
```
Failed to deploy a stack: Container wg-portal Recreate Container wg-portal Recreated Container wg-portal Starting Error response from daemon: driver failed programming external connectivity on endpoint wg-portal (4fa8fdfafd5a2ccd07f87cfdc87f04c42adc48d4c43e347c9fd59a10c8f6a8b2): failed to bind port 172.31.22.2:18887/tcp: Error starting userland proxy: listen tcp4 172.31.22.2:18887: bind: cannot assign requested address 
```

If you guys have any idea, how to solve it, and [improve the doc](https://wgportal.org/master/documentation/getting-started/docker/#wireguard-interface-handling), please tell me!

**Comment by h44z** [comment]
1. Do you have the [restore_state](https://wgportal.org/master/documentation/configuration/overview/#restore_state) configuration option set to true? This is required for WireGuard Portal to restore interface state after restart.
2. The Web UI port is incorrect; use "127.0.0.9:18888:8888/tcp". Alternatively, overwrite the [listening_address](https://wgportal.org/master/documentation/configuration/overview/#listening_address_1) in your config if needed.

**Comment by h44z** [comment]
Hmm, I don't know why your interface is not available. Usually, if [restore_state](https://wgportal.org/master/documentation/configuration/overview/#restore_state) is set to _true_ and you restart the Docker container (use docker compose down and up, not stop/start), all interfaces are recreated.

I am closing this issue for now. If you have any new insights, feel free to post a comment.

**Comment by PizzaProgram** [comment]
### This is a complete guide, how to secure your WG-Portal server:
- inside docker,
- in bridged mode,
- using random ports,
- bind the web interface to localhost,
- and finally share the web portal via SSH to your PC directly.
    (Not allowing to open it from the outside internet.)

> [!Warning]
> If you are exposing the Web-UI to the open internet, always use a reverse proxy + SSL (httpS)!
> _(More info [here...](https://wgportal.org/master/documentation/getting-started/reverse-proxy/) )_

### Security considerations:
1. Using default port numbers (copied from example) is dangerous, because a hacker will try to attack through `8888` and `8080` first!
    - **Solution:** use a random port for the web! 
    _For example:_ `listening_address: :29761`
    - **Tip:** using a known port for the WG0 interface has a benefit that clients can connect to it from everywhere.  
    Even from a hotel, where only 3-4 standard ports are allowed. 
    _For example:_ `start_listen_port: 993` for WG0

2. Docker helps to isolate WG-portal from your host server, especially in bridged mode.
  (Because it will use a separate network subnet. In the following example: `172.31.22.0/24`)

3. It is also wise to change default SSH port of the server from `22` -> to something else. (Not `2222` either! )

# The `config.yaml` file: 

<details>

```yaml
# This is a bit more secure configuration example 
core:
  admin_user:     ****** # <--- FILL_THIS
  admin_password: ****** # <--- FILL_THIS
  editable_keys: true
  create_default_peer: false
  create_default_peer_on_creation: false
  re_enable_peer_after_user_enable: true
  delete_peer_after_user_deleted: false
  self_provisioning_allowed: false
  import_existing: false
  restore_state: true

advanced:
  log_level: info
  log_pretty: true
  log_json: false
  start_listen_port: ****** # <--- FILL_THIS number 
  start_cidr_v4:     ****** # <--- FILL_THIS Like: 100.111.12.0/24
  start_cidr_v6:     ****** # <--- FILL_THIS Like: fe80:d3ad:c0de:1234::0/64
  use_ip_v6: true
  config_storage_path: ""
  expiry_check_interval: 30m
  rule_prio_offset: 20000
  api_admin_only: true

database:
  debug: false
#  slow_query_threshold: 0
  type: sqlite
  dsn: data/sqlite.db

statistics:
  use_ping_checks: true
  ping_check_workers: 16
  ping_unprivileged: false
  ping_check_interval: 4s
  data_collection_interval: 1m
  collect_interface_data: true
  collect_peer_data: true
  collect_audit_data: true
  listening_address: 8787 # <--- change this too! To bind to localhost: "127.9.9.9:8787"  ... or via docker

mail:
  host: 127.0.0.1
  port: 25
  encryption: none
  cert_validation: true
  username: ""
  password: ""
  auth_type: plain
  from: Wireguard Portal <noreply@wireguard.local>
  link_only: false

auth:
  oidc: []
  oauth: []
  ldap: []

web:
  listening_address: :29761             # Note: keep the ":" sign before the number! 
  external_url: http://127.9.9.9:29761 # this will bind to localhost. The port must be the same as the "listening_address"
  site_company_name: WireGuard Portal
  site_title:        WireGuard Portal
  session_identifier: wgPortalSession   # You may change this too
  session_secret: very_secret           # CHANGE THIS! 
  csrf_secret:    extremely_secret      # CHANGE THIS!
  request_logging: false
  cert_file: ""
  key_File: ""

webhook:
  url: ""
  authentication: ""
  timeout: 10s

```

</details>

# The docker stack compose text:

<details>

```yaml
services:
  wg-portal:
    image: wgportal/wg-portal:stable # You may change ":stable" to ":v2" or ":latest"
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    cap_add:
      - NET_ADMIN
    volumes:
      # host path : container path
      - ./wg/data:/app/data
      - ./wg/config:/app/config # here is your config.yaml file
    ports:
      # host port : container port
      # WireGuard port, needs to match the port in wg-portal interface config (add one port mapping for each interface)
      - "993:993/udp"  # The first is usually "wg0" virtual ethernet interface
      - "994:994/udp"  # Note: These ports must be allowed at firewall too !

      # The Web UI port. Must be the same as 
      - "127.9.9.9:29761:29761/tcp"  # <--- This is the web port, that is binded to localhost. This way it will not be open to the internet.

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wg-docker-nat

networks:
  wg-docker-nat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.22.0/24 # You can change this subnet, if other docker containers are already using it.

```

</details>

# How to bind the Web-UI port to your Windows using SSH: 

1. Download and install: [Bitwise SSH client](https://bitvise.com/ssh-client-download) . 
  _(It is an advanced version of Putty. It is free to use for both personal + business.)_

2. On the [C2S] tab, set port forwarding:
    Full explanation is [here...](https://bitvise.com/port-forwarding)

| Listen interface | port | Destination host | port | comment |
| --- | --- | --- | --- | --- | 
| 127.9.9.9 | 29761 | 127.9.9.9  | 29761 | wg-portal |

3. Open WG-portal in your Brower at:
    [http://127.9.9.9:29761](http://127.9.9.9:29761)
