### ISSUE TITLE
WG routes are removed

### ISSUE THREAD

**Issue by aviatorhh** [h44z/wg-portal#438]
```yaml
core:
  admin_user: ***
  admin_password: ***
  admin_api_token: ***
  import_existing: true
  create_default_peer: false
  self_provisioning_allowed: true

web:
  site_title: My WireGuard Server
  site_company_name: NJK
  listening_address: :9080
  external_url: https://***:9080
  csrf_secret: ***
  session_secret: ***
  request_logging: true
  cert_file: /etc/ssl/av8r.pro.cert
  key_file: /etc/ssl/av8r.pro.key

advanced:
  log_level: info
  log_pretty: true
  log_json: false
  config_storage_path: /etc/wireguard
  expiry_check_interval: 1m

database:
  debug: true
  type: sqlite
  dsn: data/sqlite.db
```

**Describe the bug**
When changing/saving a peer the wg interfaces routes go away. The routes (ip r) disappear. Restarting wg via cli restores them.
This also happens when starting/restarting wg-portal.

**Expected behavior**
Make changes and do not lose routes.

**Steps to reproduce**
Just change a peers name.

**Screenshots**
n/a

**Additional context**
RPi4, Debian 12
- Application version: 7fd2bbad029d7a2d55074ac37a2954529106ec43
- Install method: local build

It is that I get this behaviour but without any errors in the journal. How can I debug this?
