### ISSUE TITLE
New Peer not added to existing wg0.conf

### ISSUE THREAD

**Issue by smileBeda** [h44z/wg-portal#446]
When adding a new peer on the default conf that was "discovered" by WG Portal (since Wireguard was already installed on the host) that peer is not added anywhere, it only lives in the WG Portal.
It is not in the `/etc/wireguard/wg0.conf` nor anywhere else.

As such the connection can never work, even if we where able to add the tunnel to the peer's machine (which does not work either, see #445)

Where are those peers stored?

I am using a default Docker Compose file (with network_mode:host) and default configuration file (only edits are my email, password and unique seeds)

**Comment by bonddim** [comment]
Pls share your config.yml and compose file without sensitive data.

**Comment by h44z** [comment]
If you want automatic wg-quick file generation, you need to specify the [config_storage_path](https://wgportal.org/latest/documentation/configuration/overview/#config_storage_path) option in the advanced section of the configuration file.

Also, ensure that you mount a volume at that path.

e.g.:

config.yaml:
```yaml
advanced:
  config_storage_path: /etc/wireguard/
```

docker-compose.yml:
```yaml
    volumes:
      # host path : container path
      - ./wg/etc:/etc/wireguard
```

Now the wg-quick files are available in the `wg/etc` directory after you edit an interface in WireGuard Portal.


Usually, WireGuard Portal manages all the peers and interfaces internally. No wg-quick or other external tools are required. Checkout the config description (e.g. [restore_state](https://wgportal.org/latest/documentation/configuration/overview/#restore_state)) for more information.

**Comment by smileBeda** [comment]
This is still not written to file.

1. Docker Compose:
```
services:
  wg-portal:
    image: wgportal/wg-portal:v2
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    # Use host network mode for WireGuard and the UI. Ensure that access to the UI is properly secured.
    network_mode: "host"
    volumes:
      # left side is the host path, right side is the container path
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config
```

2. config.yml:
```
core:
  admin_user: [redacted]
  admin_password: [redacted]
  admin_api_token: ""
  editable_keys: true
  create_default_peer: false
  create_default_peer_on_creation: false
  re_enable_peer_after_user_enable: true
  delete_peer_after_user_deleted: false
  self_provisioning_allowed: false
  import_existing: true
  restore_state: true

advanced:
  log_level: info
  log_pretty: false
  log_json: false
  start_listen_port: 51820
  start_cidr_v4: 10.7.0.0/24
  #start_cidr_v6: fdfd:d3ad:c0de:1234::0/64
  use_ip_v6: false
  config_storage_path: "/etc/wireguard"
  expiry_check_interval: 15m
  rule_prio_offset: 20000
  route_table_offset: 20000
  api_admin_only: true

database:
  debug: false
  slow_query_threshold: "0"
  type: sqlite
  dsn: data/sqlite.db
  encryption_passphrase: [redacted]

statistics:
  use_ping_checks: true
  ping_check_workers: 10
  ping_unprivileged: false
  ping_check_interval: 1m
  data_collection_interval: 1m
  collect_interface_data: true
  collect_peer_data: true
  collect_audit_data: true
  listening_address: 172.17.0.1:8787

mail:
  host: [redacted]
  port: 587
  encryption: starttls
  cert_validation: true
  username: [redacted]
  password: [redacted]
  auth_type: login
  from: [redacted]
  link_only: false

auth:
  oidc: []
  oauth: []
  ldap: []

web:
  listening_address: 172.17.0.1:8888
  external_url: [redacted]
  site_company_name: [redacted]
  site_title: [redacted]
  session_identifier: wgPortalSession
  session_secret: [redacted]
  csrf_secret: [redacted]
  request_logging: false
  expose_host_info: false
  cert_file: ""
  key_File: ""

webhook:
  url: ""
  authentication: ""
  timeout: 10s
```

I must be doing something wrong:
- existing /etc/wireguard/wg0.conf is not updated (well, I am kind of happy about that, but still, I would expect the new peers added there)
- there is also no new file created, it seems to stay all in the database

Connections of new peers are working... but at this point I am confused as of whether I even still need local file, if I can (and should?) delete it, if my config is correct, or not

Preferably, I would want the local file synced. this because I simply do not trust the database yet.
