### ISSUE TITLE
Authentik : Login Failed - no log, no trace, no info

### ISSUE THREAD

**Issue by arnaudaprahamian** [h44z/wg-portal#451]
config.yml :
```yaml
core:
  admin_user: admin@mydomain.fr
  admin_password: <passwords>
web:
  external_url: https://wgportal.internal.mydomain.fr 
  request_logging: true
  site_company_name: mydomain.fr
  site_title: mydomain.fr - Wireguard
database:
  type: postgres
  dsn: "host=192.168.1.102 port=5432 user=wgportal password=<passwords> dbname=wgportal sslmode=disable"
  encryption_passphrase: "<key>"
mail:
  host: smtp.protonmail.ch
  port: 587
  encryption: starttls
  username: admin@mydomain.fr
  password: <passwords>
  auth_type: login
  from: admin@mydomain.fr
  link_only: false
advanced:
  log_level: info
  log_pretty: true
auth:
  oidc:
    - id: authentik
      provider_name: authentik
      display_name: Se connecter avec Authentik
      base_url: https://<authentik>/application/o/wg-portal/
      client_id: <client-id>
      client_secret: <client_secret>
      extra_scopes:
        - email, openid, profile
      field_map:
        user_identifier: sub
        email: email
        user_groups: groups
      registration_enabled: true
      log_user_info: true
      admin_mapping:
        admin_group_regex: ^Owners$  
```
Logs :
```
Container started
2025/06/06 23:40:32 INFO Starting WireGuard Portal V2... version=v2.0.2-930ef7b
2025/06/06 23:40:32 INFO  Configuration loaded! logLevel=info
2025/06/06 23:40:34 INFO  [WEBHOOK] no webhook configured, skipping event-bus subscription
2025/06/06 23:40:34 INFO  interface state restored
2025/06/06 23:40:34 INFO  started web service address=:8888
2025/06/06 23:40:34 INFO  started metrics service address=:8787
2025/06/06 23:40:34 INFO  Application startup complete
```
**Describe the bug**
When attempting to log in to WireGuard Portal via OpenID Connect (OIDC) with Authentik, I receive a "Login failed! Authentication via Oauth failed!" error message on the WireGuard Portal login page after being redirected from Authentik.

The application logs at INFO level show successful startup but no specific errors related to authentication at the time of the failure.

**Expected behavior**
I expect to successfully log in via Authentik and be redirected to the WireGuard Portal dashboard.

**Steps to reproduce**
Just try to login via "Authentik"

**Additional context**
Application version: v2.0.2-930ef7b
Install method: docker compose
OS: Unraid OS

here is the authentik claim : 
```
{
    "iss": "https://[ANONYMIZED_DOMAIN]/application/o/[ANONYMIZED_APP_SLUG]/",
    "sub": "[ANONYMIZED_SUB_ID]",
    "aud": "SH8bQdDkvUI1VMDBzBYYsF5la2lixwOqtj519nh2",
    "exp": 1749250912,
    "iat": 1749249112,
    "auth_time": 1749249112,
    "acr": "goauthentik.io/providers/oauth2/default",
    "email": "[ANONYMIZED_EMAIL]",
    "email_verified": true,
    "name": "[ANONYMIZED_NAME]",
    "given_name": "[ANONYMIZED_GIVEN_NAME]",
    "preferred_username": "[ANONYMIZED_PREFERRED_USERNAME]",
    "nickname": "[ANONYMIZED_NICKNAME]",
    "groups": [
        "[ANONYMIZED_GROUP_NAME]"
    ]
}
```
