### ISSUE TITLE
Peers generated with a non-admin account do not connect

### ISSUE THREAD

**Issue by mateo08c** [h44z/wg-portal#452]
**Describe the bug**
When I generate a peer with a non-administrator account, I notice that it does not receive any downstream data from the server. It is not visible in the `wg` command output.

However, if I grant the user admin rights and create a peer again, everything works correctly.

I want to emphasize that **`self_provisioning_allowed`** is enabled and **`create_default_peer_on_creation`** is disabled.

**Expected behavior**
The peer generated by a non-admin account should receive downstream data from the server and be visible in the `wg` command output, just like peers created by admin accounts.

**Steps to reproduce**
1. Ensure `self_provisioning_allowed` is enabled and `create_default_peer_on_creation` is disabled.
2. Log in with a non-administrator user account.
3. Generate a peer.
4. Check the peer's connectivity and visibility using the `wg` command.
5. Optionally, grant the user admin rights, generate another peer, and observe that it works as expected.

```yaml
core:
  admin_user: admin@xxxxx.lol
  admin_password: "SUPER_PASSWORD"
  admin_api_token: ""
  editable_keys: true
  create_default_peer: false
  create_default_peer_on_creation: false
  re_enable_peer_after_user_enable: true
  delete_peer_after_user_deleted: false
  self_provisioning_allowed: true
  import_existing: true
  restore_state: true

advanced:
  log_level: info
  log_pretty: false
  log_json: false
  start_listen_port: 51820
  start_cidr_v4: 10.11.12.0/24
  start_cidr_v6: fdfd:d3ad:c0de:1234::0/64
  use_ip_v6: true
  config_storage_path: ""
  expiry_check_interval: 15m
  rule_prio_offset: 20000
  route_table_offset: 20000
  api_admin_only: true

database:
  debug: false
  slow_query_threshold: "0"
  type: sqlite
  dsn: data/sqlite.db
  encryption_passphrase: ""

statistics:
  use_ping_checks: true
  ping_check_workers: 10
  ping_unprivileged: false
  ping_check_interval: 1m
  data_collection_interval: 1m
  collect_interface_data: true
  collect_peer_data: true
  collect_audit_data: true
  listening_address: :8787

mail:
  host: smtp-relay.super.lol
  port: 587
  encryption: starttls
  cert_validation: true
  username: "no-reply@xxxxx.lol"
  password: "XXXXXXXX"
  auth_type: login
  from: Wireguard Portal <no-reply@xxxxx.lol>
  link_only: false

auth:
  oidc: []
  oauth: []
  ldap: []

web:
  listening_address: :8888
  external_url: https://vpn.xxxxx.lol
  site_company_name: WireGuard Portal
  site_title: WireGuard Portal
  session_identifier: wgPortalSession
  session_secret: RANDOM
  csrf_secret: RANDOM
  request_logging: false
  expose_host_info: false
  cert_file: ""
  key_File: ""

webhook:
  url: ""
  authentication: ""
  timeout: 10s  
```

**Screenshots**

<div style="display: flex; gap: 10px;">
  <img src="https://github.com/user-attachments/assets/04bec4f5-75f2-49bc-b39a-5cc87278def3" alt="Image 1" width="300" />
  <img src="https://github.com/user-attachments/assets/55f249ff-6179-494e-b171-07af1392816f" alt="Image 2" width="300" />
</div>

**Additional context**
- Application version: v2.0.2-930ef7b
- Install method: binary
- OS: Proxmox LXC Debian 12
