### ISSUE TITLE
Restrict normal user access to only specifically defined networks

### ISSUE THREAD

**Issue by sj-louw** [h44z/wg-portal#458]
It would be great if a feature can be implemented that restricts OIDC and oauth users, based on group, to what networks they have access.

The use-case for this is when for example you have a company VPN server running wireguard portal, that provides access to various AWS VPCs / networks and users are restricted based on which group they are in.

From what I understand, it looks like the UI already allows for this, but this solution makes those access networks more dynamic. Essentially when the user logs in via SSO, a peer is created and the correct network access is granted based on OIDC group the user belongs to. Assuming the default iptables outbound is set to block all requests.

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/6535b578-6ef8-41ba-8239-0769d0225d47" />

An example partial config entry might look something like this:

```
auth:
  oidc:
    - id: okta
      .....
      admin_mapping:
        admin_group_regex: ^the-admin-group$
      user_allowed_networks:
         SomeOIDCGroup1:
           - 1.1.1.1/24
           - 2.2.2.2/24
         SomeOIDCGroup2:
           - 3.3.3.3/24
         SomeOIDCGroup3:
           - 4.4.4.4/24
           - 5.5.5.5/24
           - 6.6.6.6/24
       .....
```

Would something like this be feasible to implement, to restrict users only to certain networks? One might have to add additional iptables rules to block users to networks other than these?
