### ISSUE TITLE
config.yml structure

### ISSUE THREAD

**Issue by valireality** [h44z/wg-portal#5]
Hi,

how config.yml file should look like, something like this:
```
environment:
     - LISTENING_ADDRESS=:8080
     - EXTERNAL_URL=https://wg-test.test.com
     - WEBSITE_TITLE=TEST VPN Portal
     - COMPANY_NAME=TEST
     - MAIL_FROM=TEST
     - ADMIN_USER=test@test.com
     - ADMIN_PASS=test
     - EDITABLE_KEYS=true
     - CREATE_DEFAULT_PEER=false
     - LDAP_ENABLED=false
```

every time i start the portal with go `run cmd/wg-portal/main.go` or execute the binary file, i got message:
`unable to load config.yml file: failed to open config file config.yml: open config.yml: no such file or directory, using default configuration...`

**Comment by h44z** [comment]
Hi,

a sample config.yml would look like:

````yaml
core:
  listeningAddress: :8080
  externalUrl: https://wg-test.test.com
  adminUser: test@test.com
  adminPass: test
  editableKeys: true
  createDefaultPeer: false
  ldapEnabled: false
database:
  typ: sqlite
  database: data/wg_portal.db
email:
  host: 123.123.123.13
  port: 25
````

The names of the properties can be found here: [https://github.com/h44z/wg-portal/blob/master/internal/server/configuration.go#L56](https://github.com/h44z/wg-portal/blob/master/internal/server/configuration.go#L56) and in sub-files like for example [here](https://github.com/h44z/wg-portal/blob/master/internal/common/db.go#L24). For the yaml config file, the names in the yaml tags are relevant. For environment configuration you have to consider the names in the envconfig tags.

Also make sure that the config.yml is located in the same directory as your executable. Also use this directory as working-path.
If you want to specify the path to the config.yml file you can also use the environment variable **CONFIG_FILE**. For example:

````bash
CONFIG_FILE=/home/test/config.yml go run cmd/wg-portal/main.go
````

**Comment by valireality** [comment]
Thank you very much for your effort.

config.yml works great, except the LDAP section:
`skipping provider registration: unable to open ldap connection: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09041C, comment: AcceptSecurityContext error, data 52e, v4563` 

configurations look like this:
```yaml
ldap:
  url: ldap://10.10.10.10:389
  basedn: DC=test,DC=test
  starttls: false
  binduser: wireguard@test.test
  bindpass: test
  adminldapgroup: CN=WireGuardAdmins,CN=Users,DC=test,DC=test
  type: AD
  userclass: organizationalPerson
  emailattribute: mail
  firstnameattribute: givenName
  lastnameattribute: sn
  phoneattribute: telephoneNumber
  groupmemberattribute: memberOf
  disabledattribute: userAccountControl
```
Tested with ldapsearch and results are correct.

Thanks

**Comment by h44z** [comment]
Hi,

the yaml names for the ldap configuration are not correct. You can find them [here](https://github.com/h44z/wg-portal/blob/master/internal/ldap/config.go#L10).

Your configuration should look like this:

````yaml
ldap:
  url: ldap://10.10.10.10:389
  dn: DC=test,DC=test
  startTLS: false
  user: wireguard@test.test
  pass: test
  adminGroup: CN=WireGuardAdmins,CN=Users,DC=test,DC=test
  typ: AD
  userClass: organizationalPerson
  attrEmail: mail
  attrFirstname: givenName
  attrLastname: sn
  attrPhone: telephoneNumber
  attrGroups: memberOf
  attrDisabled: userAccountControl
````


PS: for anyone having trouble finding the correct yaml names, here are the files where you can find the specified yaml and environment tag names:
 - [Mail settings](https://github.com/h44z/wg-portal/blob/master/internal/common/email.go#L13)
 - [WireGuard settings](https://github.com/h44z/wg-portal/blob/master/internal/wireguard/config.go#L5)
 - [LDAP settings](https://github.com/h44z/wg-portal/blob/master/internal/ldap/config.go#L10)
 - [Database settings](https://github.com/h44z/wg-portal/blob/master/internal/common/db.go#L24)
 - [Core settings](https://github.com/h44z/wg-portal/blob/master/internal/server/configuration.go#L56)
