### ISSUE TITLE
FATA: failed to get peer list for device wg0

### ISSUE THREAD

**Issue by Vuty-A** [h44z/wg-portal#69]
Please tell me how to solve the problem, after reboot the docker container does not rise? 
I am using the half-last version of the project.
 
`wg-portal    | FATA[2021-11-09 13:37:55] setup failed: unable to setup peer manager: unable to initialize peer manager: failed to get peer list for device wg0: could not get WireGuard device: file does not exist`

**Comment by h44z** [comment]
seems that the WireGuard interface wg0 on your host system does not exist or is not up

**Comment by Vuty-A** [comment]
Thanks for the answer. 
The interface is created and even works without problems. Created in the /etc/wireguard/wg0.conf directory.
I deployed your project through Docker using the latest version. 
Command "docker-compose -f docker-compose.yml up -d"

The docker-compose.yml itself looks like this:

```
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:1.0.6
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    ports:
      - '8123:8123'
    environment:
      - EXTERNAL_URL=http://localhost:8123
      - ADMIN_USER=admin@domain.com
      - ADMIN_PASS=supersecret
      - CONFIG_FILE=/app/config.yml
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard

```
When the web interface is deployed for the first time, everything works. But after rebooting the system, this problem arises.
